name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get Release by Tag
      id: get_release_by_tag
      uses: jonfriesen/get-release-by-tag@v0.0.11
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}

    - name: Build
      run: go build -v -o testbin .
    
    - name: Run
      run: |
        chmod +x testbin
        ./testbin
